dataset: NCI1
aug: baseline
model_type: gnn
gnn_type: gcn
gnn_virtual_node: false
runs: 1
epochs: 200
seed: 12344
scheduler: plateau
#gnn_emb_dim: 310 # For ~500k total parameters
gnn_emb_dim: 400 # For ~800k total parameters