dataset: NCI109
aug: baseline
model_type: gnn
gnn_type: gcn
gnn_virtual_node: false
runs: 1
epochs: 200
seed: 12344
scheduler: plateau
#gnn_emb_dim: 220 # For ~500k total params
gnn_emb_dim: 280 # For ~800k total params
gnn_num_layer: 10